services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logosfm-website
    ports:
      - "7777:8000"
    restart: unless-stopped
    networks:
      - logosfm-network

networks:
  logosfm-network:
    driver: bridge

