services:
  azurecast:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: azurecast-streaming
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./data:/var/www/azurecast
    networks:
      - azurecast-network

networks:
  azurecast-network:
    driver: bridge

